# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Funny' do

pod 'AFNetworking'
pod 'SDWebImage/GIF'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'DACircularProgress'
 
end
